### ISSUE TITLE
sorry， in my win10 64 laptop find some problem

### ISSUE THREAD

**Issue by Ernest861** [wshuyi/markdown2slides#1]
![image](https://user-images.githubusercontent.com/28133972/51437633-d2b4f180-1cdb-11e9-9869-b5d9c6247242.png)
(base) D:\fMRITools\CA\markdown2slides>python md2slide.py example/myslide.md
Traceback (most recent call last):
  File "md2slide.py", line 16, in <module>
    converter = MarkdownRevealjsConverter(md_fname, **config)
  File "D:\fMRITools\CA\markdown2slides\revealjs_converter.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "D:\fMRITools\CA\markdown2slides\converter.py", line 24, in __init__
    self.config = json.load(f)
  File "C:\Users\zhdivel\Anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x89 in position 113: illegal multibyte sequence

**Comment by zi-NaN** [comment]
It seems that the Python version you donwload is 2.* and there is no Python 3 in your computer. Maybe you can donwload Python3 and try it again.

**Comment by Ernest861** [comment]
![image](https://user-images.githubusercontent.com/28133972/51505139-d2be0a00-1e1f-11e9-9e50-607afeadef91.png)
thanks for your advice. when I call python, the python vision is 3.7

**Comment by wshuyi** [comment]
In this case, just use "python" instead of "python 3" and see if that works.

**Comment by zi-NaN** [comment]
> In this case, just use "python" instead of "python 3" and see if that works.

He has tried with `python` command (in the first picture) and it throws a decode exception.

**Comment by Wangliumeng** [comment]
I have same problem...

**Comment by zi-NaN** [comment]
Can you go to the line 23 of `conventer.py` and pass `encoding` parameter to the open function? Something like this, `with open(config_json_fname, encoding='latin1') as f:`. You can try other encoding types, for example, `utf8`. I am not sure which kind of encoding types can solve the problem but it seems that it is an encoding problem.
